name: wedding
description: "Soogil Wedding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  go_router: ^16.1.0
#  rename: ^3.1.0
  photo_view: ^0.15.0
#  google_fonts: ^6.3.0
  timeline_tile: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  json_annotation: ^4.9.0
  change_app_package_name: ^1.5.0

flutter:

  uses-material-design: true

  assets:
    - assets/hero.png
    - assets/hero1.jpg
    - assets/hero2.jpg
    - assets/parent_kim.png
    - assets/parent_you.png
    - assets/kim.jpg
    - assets/you.jpg
    - assets/flac/couple.flac
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/notoSans/NotoSans-Bold.ttf
          weight: 700
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/indieFlower/IndieFlower-Regular.ttf
          weight: 400
    - family: Gamja
      fonts:
        - asset: assets/fonts/gamja/GamjaFlower-Regular.ttf
          weight: 400
    - family: Bareun
      fonts:
        - asset: assets/fonts/bareun/BareunBatangM.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


