name: wedding
description: "Soogil Wedding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  go_router: ^16.1.0
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  timeline_tile: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_screenutil: ^5.9.0
  just_audio: ^0.9.36
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  change_app_package_name: ^1.5.0

flutter:

  uses-material-design: true

  assets:
    - assets/hero1.jpg
    - assets/hero2.jpg
    - assets/parent_kim.png
    - assets/parent_you.png
    - assets/kim.jpg
    - assets/you.jpg
    - assets/mp3/couple.mp3
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/notoSans/NotoSans-Bold.ttf
          weight: 700
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/indieFlower/IndieFlower-Regular.ttf
          weight: 400
    - family: Bareun
      fonts:
        - asset: assets/fonts/bareun/BareunBatangM.ttf
          weight: 400
